# Generated by Django 5.0.1 on 2024-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('investment_range', models.CharField(choices=[('500000-1000000', 'От 500.000 до 1.000.000'), ('300000-800000', 'От 300.000 до 800.000')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('password_confirmation', models.CharField(max_length=100)),
                ('receive_interesting_offers', models.BooleanField(default=False, help_text='Получать интересные предложения на почту?')),
            ],
        ),
    ]
