# Generated by Django 5.0.1 on 2024-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('investment_range', models.CharField(choices=[('no', 'Еще нет, собираюсь на вашей платформе'), ('yes', 'Да, уже привлекал инвестиции')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('password_confirmation', models.CharField(max_length=100)),
                ('receive_interesting_offers', models.BooleanField(default=False, help_text='Получать интересные предложения на почту?')),
            ],
        ),
    ]
