# Generated by Django 5.0.1 on 2024-02-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_businessman'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='businessman',
            name='interest_sectors',
            field=models.ManyToManyField(blank=True, to='users.interestsector'),
        ),
    ]
