# Generated by Django 5.0.2 on 2024-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_businessman_receive_interesting_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='verification',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='businessman',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
