# Generated by Django 5.0.1 on 2024-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_interestsector_businessman_interest_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='interest_sectors',
        ),
        migrations.RemoveField(
            model_name='businessman',
            name='investment_range',
        ),
        migrations.AddField(
            model_name='businessman',
            name='business_range',
            field=models.CharField(choices=[('no', 'Еще нет, собираюсь на вашей платформе'), ('yes', 'Да, уже привлекал инвестиции')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='interest_sectors',
            field=models.ManyToManyField(blank=True, to='registration.interestsector'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='receive_interesting_offers',
            field=models.BooleanField(default=False, help_text='Получать полезные материалы по привлечению инвестицый'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_range',
            field=models.CharField(choices=[('100000-500000', 'От 100.000 до 500.000'), ('500000-1000000', 'От 500.000 до 1.000.000'), ('1000000-1500000', 'От 1.000.000 до 1.500.000')], max_length=20),
        ),
    ]
