# Generated by Django 4.2.10 on 2024-02-07 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_businessman_interest_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='username',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='username',
        ),
        migrations.AddField(
            model_name='businessman',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businessman_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
