# Generated by Django 4.2.10 on 2024-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_businessman_username_remove_investor_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman',
            name='password',
        ),
        migrations.RemoveField(
            model_name='businessman',
            name='password_confirmation',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='password_confirmation',
        ),
        migrations.AddField(
            model_name='investor',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='businessman',
            name='interest_sectors',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='interest_sectors',
        ),
        migrations.AddField(
            model_name='businessman',
            name='interest_sectors',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='interest_sectors',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
